version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: ecom_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      app:
        condition: service_started
    networks:
      - ecom_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:17-alpine
    container_name: ecom_postgres
    restart: unless-stopped
    env_file:
      - deployment/.env
    volumes:
      - /mnt/postgres_data/pgdata:/var/lib/postgresql/data
    networks:
      - ecom_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    image: rickylyxon/ecom_clover:latest
    container_name: ecom_app
    env_file:
      - deployment/.env
    networks:
      - ecom_network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5 
      start_period: 60s 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ecom_network:
    driver: bridge

volumes:
  nginx_logs:
    driver: local
