version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: ecom_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cloudflare-ips.conf:/etc/nginx/conf.d/cloudflare-ips.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - ecom_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    image: rickylyxon/ecom_clover:latest
    container_name: ecom_app
    env_file:
      - deployment/.env
    networks:
      - ecom_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ecom_network:
    driver: bridge

volumes:
  nginx_logs:
    driver: local