version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: ecom_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - ecom_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:17-alpine
    container_name: ecom_postgres
    restart: unless-stopped
    env_file:
      - deployment/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecom_network
    ports:
      - "5432:5432"

  app:
    image: rickylyxon/ecom_clover:latest
    container_name: ecom_app
    env_file:
      - deployment/.env
    networks:
      - ecom_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ecom_network:
    driver: bridge

volumes:
  nginx_logs:
    driver: local
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/postgres_data
